repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check (uv.lock)
        entry: uv run --locked ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: Ruff format (uv.lock)
        entry: uv run --locked ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
